import { initializeApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  addDoc, 
  getDocs, 
  query, 
  orderBy, 
  deleteDoc, 
  doc,
  setDoc,
  getDoc
} from 'firebase/firestore';
import { getAuth } from 'firebase/auth';
import { Lead } from './types';
import config from '../firebase-applet-config.json';

// Initialize Firebase using the configuration generated by AI Studio
const app = initializeApp(config);
export const db = getFirestore(app, config.firestoreDatabaseId);
export const auth = getAuth();

enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid || null,
      email: auth.currentUser?.email || null,
      emailVerified: auth.currentUser?.emailVerified || null,
      isAnonymous: auth.currentUser?.isAnonymous || null,
      tenantId: auth.currentUser?.tenantId || null,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

const LEADS_COLLECTION = 'leads';

// Save lead to Firestore
export async function saveLeadToFirestore(name: string, contact: string): Promise<Lead> {
  const timestamp = new Date().toLocaleString('pt-BR', { 
    day: '2-digit', 
    month: '2-digit', 
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const leadData = {
    name,
    contact,
    date: timestamp,
    createdAt: new Date().getTime()
  };

  try {
    const docRef = await addDoc(collection(db, LEADS_COLLECTION), leadData);
    return {
      id: docRef.id,
      name,
      contact,
      date: timestamp
    };
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, LEADS_COLLECTION);
    throw error;
  }
}

// Fetch all leads from Firestore
export async function fetchLeadsFromFirestore(): Promise<Lead[]> {
  try {
    const q = query(collection(db, LEADS_COLLECTION), orderBy('createdAt', 'desc'));
    const querySnapshot = await getDocs(q);
    const leads: Lead[] = [];
    querySnapshot.forEach((doc) => {
      const data = doc.data();
      leads.push({
        id: doc.id,
        name: data.name || '',
        contact: data.contact || '',
        date: data.date || ''
      });
    });
    return leads;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, LEADS_COLLECTION);
    return [];
  }
}

// Delete lead from Firestore
export async function deleteLeadFromFirestore(id: string): Promise<void> {
  try {
    await deleteDoc(doc(db, LEADS_COLLECTION, id));
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `${LEADS_COLLECTION}/${id}`);
  }
}

// Save logo image base64 data to Firestore settings
export async function saveLogoToFirestore(base64Data: string, lightBase64Data?: string): Promise<void> {
  const settingsPath = 'settings/logo';
  try {
    const settingsRef = doc(db, 'settings', 'logo');
    await setDoc(settingsRef, {
      base64: base64Data,
      lightBase64: lightBase64Data || '',
      updatedAt: new Date().getTime()
    }, { merge: true });
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, settingsPath);
  }
}

// Fetch logo image base64 data from Firestore settings
export async function fetchLogoFromFirestore(): Promise<{ base64: string; lightBase64: string } | null> {
  const settingsPath = 'settings/logo';
  try {
    const settingsRef = doc(db, 'settings', 'logo');
    const docSnap = await getDoc(settingsRef);
    if (docSnap.exists()) {
      const data = docSnap.data();
      return {
        base64: data.base64 || '',
        lightBase64: data.lightBase64 || ''
      };
    }
    return null;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, settingsPath);
    return null;
  }
}
