import { initializeApp } from 'firebase/app';
import { 
  getFirestore, 
  collection, 
  addDoc, 
  getDocs, 
  query, 
  orderBy, 
  deleteDoc, 
  doc,
  setDoc,
  getDoc
} from 'firebase/firestore';
import { getAuth, signInWithPopup, GoogleAuthProvider, onAuthStateChanged, User } from 'firebase/auth';
import { Lead } from './types';
import config from '../firebase-applet-config.json';

// Initialize Firebase using the configuration generated by AI Studio
const app = initializeApp(config);
export const db = getFirestore(app, (config as any).firestoreDatabaseId);
export const auth = getAuth();

enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errorMessage = error instanceof Error ? error.message : String(error);
  const isOffline = errorMessage.toLowerCase().includes('offline') || errorMessage.toLowerCase().includes('network');

  const errInfo: FirestoreErrorInfo = {
    error: errorMessage,
    authInfo: {
      userId: auth.currentUser?.uid || null,
      email: auth.currentUser?.email || null,
      emailVerified: auth.currentUser?.emailVerified || null,
      isAnonymous: auth.currentUser?.isAnonymous || null,
      tenantId: auth.currentUser?.tenantId || null,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  };

  if (isOffline) {
    console.warn(`Firestore Offline/Network Warning (${operationType} on ${path}): ${errorMessage}`);
    return;
  }

  console.error('Firestore Error: ', JSON.stringify(errInfo));

  // Only throw for write/mutate operations so that calling reads can fallback gracefully
  if (operationType !== OperationType.GET && operationType !== OperationType.LIST) {
    throw new Error(JSON.stringify(errInfo));
  }
}

// Timeout helper to prevent infinite waiting on Firestore connections
export function withTimeout<T>(promise: Promise<T>, timeoutMs: number = 6000, operationName: string = 'Operação'): Promise<T> {
  let timeoutId: NodeJS.Timeout;
  const timeoutPromise = new Promise<never>((_, reject) => {
    timeoutId = setTimeout(() => {
      reject(new Error(`Timeout na operação '${operationName}' após ${timeoutMs / 1000}s. Verifique se o banco de dados do Firebase (Firestore) foi provisionado e se o plano gratuito não atingiu o limite de cotas.`));
    }, timeoutMs);
  });

  return Promise.race([
    promise.then((result) => {
      clearTimeout(timeoutId);
      return result;
    }),
    timeoutPromise
  ]);
}

const LEADS_COLLECTION = 'leads';

// Save lead to Firestore
export async function saveLeadToFirestore(
  name: string, 
  contact: string,
  typology?: string,
  project?: string
): Promise<Lead> {
  const timestamp = new Date().toLocaleString('pt-BR', { 
    day: '2-digit', 
    month: '2-digit', 
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const leadData = {
    name,
    contact,
    typology: typology || '',
    project: project || '',
    date: timestamp,
    createdAt: new Date().getTime()
  };

  try {
    const docRef = await withTimeout(
      addDoc(collection(db, LEADS_COLLECTION), leadData),
      6000,
      'salvar lead'
    );
    return {
      id: docRef.id,
      name,
      contact,
      date: timestamp,
      typology: typology || '',
      project: project || ''
    };
  } catch (error) {
    handleFirestoreError(error, OperationType.CREATE, LEADS_COLLECTION);
    throw error;
  }
}

// Fetch all leads from Firestore
export async function fetchLeadsFromFirestore(): Promise<Lead[]> {
  try {
    const q = query(collection(db, LEADS_COLLECTION), orderBy('createdAt', 'desc'));
    const querySnapshot = await withTimeout(
      getDocs(q),
      6000,
      'buscar leads'
    );
    const leads: Lead[] = [];
    querySnapshot.forEach((doc) => {
      const data = doc.data();
      leads.push({
        id: doc.id,
        name: data.name || '',
        contact: data.contact || '',
        date: data.date || '',
        typology: data.typology || '',
        project: data.project || ''
      });
    });
    return leads;
  } catch (error) {
    handleFirestoreError(error, OperationType.LIST, LEADS_COLLECTION);
    return [];
  }
}

// Delete lead from Firestore
export async function deleteLeadFromFirestore(id: string): Promise<void> {
  try {
    await withTimeout(
      deleteDoc(doc(db, LEADS_COLLECTION, id)),
      6000,
      'excluir lead'
    );
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `${LEADS_COLLECTION}/${id}`);
  }
}

// Save logo image base64 data to Firestore settings
export async function saveLogoToFirestore(base64Data: string, lightBase64Data?: string): Promise<void> {
  const settingsPath = 'settings/logo';
  try {
    const settingsRef = doc(db, 'settings', 'logo');
    await setDoc(settingsRef, {
      base64: base64Data,
      lightBase64: lightBase64Data || '',
      updatedAt: new Date().getTime()
    }, { merge: true });
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, settingsPath);
  }
}

// Fetch logo image base64 data from Firestore settings
export async function fetchLogoFromFirestore(): Promise<{ base64: string; lightBase64: string } | null> {
  const settingsPath = 'settings/logo';
  try {
    const settingsRef = doc(db, 'settings', 'logo');
    const docSnap = await getDoc(settingsRef);
    if (docSnap.exists()) {
      const data = docSnap.data();
      return {
        base64: data.base64 || '',
        lightBase64: data.lightBase64 || ''
      };
    }
    return null;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, settingsPath);
    return null;
  }
}

// Google Auth for Workspace Integration
const googleProvider = new GoogleAuthProvider();
googleProvider.addScope('https://www.googleapis.com/auth/spreadsheets');
googleProvider.addScope('https://www.googleapis.com/auth/drive.file');

let isSigningIn = false;
let cachedAccessToken: string | null = null;

export const initGoogleAuth = (
  onAuthSuccess?: (user: User, token: string) => void,
  onAuthFailure?: () => void
) => {
  return onAuthStateChanged(auth, async (user) => {
    if (user) {
      if (cachedAccessToken) {
        if (onAuthSuccess) onAuthSuccess(user, cachedAccessToken);
      } else if (!isSigningIn) {
        cachedAccessToken = null;
        if (onAuthFailure) onAuthFailure();
      }
    } else {
      cachedAccessToken = null;
      if (onAuthFailure) onAuthFailure();
    }
  });
};

export const googleSignIn = async (): Promise<{ user: User; accessToken: string } | null> => {
  try {
    isSigningIn = true;
    const result = await signInWithPopup(auth, googleProvider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Não foi possível obter o token de acesso do Google.');
    }
    cachedAccessToken = credential.accessToken;
    return { user: result.user, accessToken: cachedAccessToken };
  } catch (error: any) {
    console.error('Google Sign-in error:', error);
    throw error;
  } finally {
    isSigningIn = false;
  }
};

export const getCachedAccessToken = (): string | null => {
  return cachedAccessToken;
};

export const googleSignOut = async () => {
  await auth.signOut();
  cachedAccessToken = null;
};

// Google Sheets Firestore Settings persistence
export interface SheetsConfig {
  spreadsheetId: string;
  spreadsheetUrl: string;
  lastSyncedAt?: number;
}

export async function saveSheetsConfig(configData: SheetsConfig): Promise<void> {
  const settingsPath = 'settings/sheets';
  try {
    const settingsRef = doc(db, 'settings', 'sheets');
    await setDoc(settingsRef, configData, { merge: true });
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, settingsPath);
  }
}

export async function fetchSheetsConfig(): Promise<SheetsConfig | null> {
  const settingsPath = 'settings/sheets';
  try {
    const settingsRef = doc(db, 'settings', 'sheets');
    const docSnap = await getDoc(settingsRef);
    if (docSnap.exists()) {
      const data = docSnap.data();
      return {
        spreadsheetId: data.spreadsheetId || '',
        spreadsheetUrl: data.spreadsheetUrl || '',
        lastSyncedAt: data.lastSyncedAt || undefined
      };
    }
    return null;
  } catch (error) {
    handleFirestoreError(error, OperationType.GET, settingsPath);
    return null;
  }
}

// Google Sheets API integrations
export async function createNewGoogleSpreadsheet(accessToken: string): Promise<{ id: string; url: string }> {
  const response = await fetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      properties: {
        title: 'Locus Living - Leads da Lista de Espera'
      }
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Erro ao criar planilha: ${errText}`);
  }

  const data = await response.json();
  return {
    id: data.spreadsheetId,
    url: data.spreadsheetUrl
  };
}

export async function syncLeadsToSpreadsheet(
  spreadsheetId: string, 
  leads: Lead[], 
  accessToken: string
): Promise<void> {
  // Convert leads to values array
  // Format columns: Nome, Contato, Tipologia, Empreendimento, Data Cadastro
  const values = [
    ['Nome', 'Contato', 'Tipologia', 'Empreendimento', 'Data de Cadastro'],
    ...leads.map(lead => [
      lead.name,
      lead.contact,
      lead.typology || '',
      lead.project || '',
      lead.date
    ])
  ];

  // We write/overwrite the whole grid starting from cell A1 of the first sheet
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/A1?valueInputOption=USER_ENTERED`;
  const response = await fetch(url, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      range: 'A1',
      majorDimension: 'ROWS',
      values: values
    })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Erro ao enviar dados para a planilha: ${errText}`);
  }
}

